/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AssessmentRouteImport } from './routes/assessment'
import { Route as BibleRouteRouteImport } from './routes/bible/route'
import { Route as BuyingRouteImport } from './routes/buying'
import { Route as DoctrineRouteImport } from './routes/doctrine'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FoodDonorsRouteImport } from './routes/food-donors'
import { Route as GiveRouteImport } from './routes/give'
import { Route as HappeningsRouteImport } from './routes/happenings'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnderstandingTheBibleRouteImport } from './routes/understanding-the-bible'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminNotifyRouteImport } from './routes/admin/notify'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as BibleIndexRouteImport } from './routes/bible/index'
import { Route as BibleSlugRouteImport } from './routes/bible/$slug'
import { Route as GiveThanksRouteImport } from './routes/give.thanks'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentRoute = AssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const BibleRouteRoute = BibleRouteRouteImport.update({
  id: '/bible',
  path: '/bible',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyingRoute = BuyingRouteImport.update({
  id: '/buying',
  path: '/buying',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctrineRoute = DoctrineRouteImport.update({
  id: '/doctrine',
  path: '/doctrine',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodDonorsRoute = FoodDonorsRouteImport.update({
  id: '/food-donors',
  path: '/food-donors',
  getParentRoute: () => rootRouteImport,
} as any)
const GiveRoute = GiveRouteImport.update({
  id: '/give',
  path: '/give',
  getParentRoute: () => rootRouteImport,
} as any)
const HappeningsRoute = HappeningsRouteImport.update({
  id: '/happenings',
  path: '/happenings',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnderstandingTheBibleRoute = UnderstandingTheBibleRouteImport.update({
  id: '/understanding-the-bible',
  path: '/understanding-the-bible',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNotifyRoute = AdminNotifyRouteImport.update({
  id: '/notify',
  path: '/notify',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BibleIndexRoute = BibleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibleRouteRoute,
} as any)
const BibleSlugRoute = BibleSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BibleRouteRoute,
} as any)
const GiveThanksRoute = GiveThanksRouteImport.update({
  id: '/thanks',
  path: '/thanks',
  getParentRoute: () => GiveRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bible': typeof BibleRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/assessment': typeof AssessmentRoute
  '/buying': typeof BuyingRoute
  '/doctrine': typeof DoctrineRoute
  '/donate': typeof DonateRoute
  '/food-donors': typeof FoodDonorsRoute
  '/give': typeof GiveRouteWithChildren
  '/happenings': typeof HappeningsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/organizations': typeof OrganizationsRoute
  '/pantry': typeof PantryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/understanding-the-bible': typeof UnderstandingTheBibleRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/staff': typeof AdminStaffRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin/': typeof AdminIndexRoute
  '/bible/': typeof BibleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/assessment': typeof AssessmentRoute
  '/buying': typeof BuyingRoute
  '/doctrine': typeof DoctrineRoute
  '/donate': typeof DonateRoute
  '/food-donors': typeof FoodDonorsRoute
  '/give': typeof GiveRouteWithChildren
  '/happenings': typeof HappeningsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/organizations': typeof OrganizationsRoute
  '/pantry': typeof PantryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/understanding-the-bible': typeof UnderstandingTheBibleRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/staff': typeof AdminStaffRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin': typeof AdminIndexRoute
  '/bible': typeof BibleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/bible': typeof BibleRouteRouteWithChildren
  '/apps': typeof AppsRoute
  '/assessment': typeof AssessmentRoute
  '/buying': typeof BuyingRoute
  '/doctrine': typeof DoctrineRoute
  '/donate': typeof DonateRoute
  '/food-donors': typeof FoodDonorsRoute
  '/give': typeof GiveRouteWithChildren
  '/happenings': typeof HappeningsRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/mission': typeof MissionRoute
  '/organizations': typeof OrganizationsRoute
  '/pantry': typeof PantryRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/understanding-the-bible': typeof UnderstandingTheBibleRoute
  '/admin/notify': typeof AdminNotifyRoute
  '/admin/staff': typeof AdminStaffRoute
  '/bible/$slug': typeof BibleSlugRoute
  '/give/thanks': typeof GiveThanksRoute
  '/admin/': typeof AdminIndexRoute
  '/bible/': typeof BibleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bible'
    | '/apps'
    | '/assessment'
    | '/buying'
    | '/doctrine'
    | '/donate'
    | '/food-donors'
    | '/give'
    | '/happenings'
    | '/join'
    | '/login'
    | '/mission'
    | '/organizations'
    | '/pantry'
    | '/privacy'
    | '/terms'
    | '/understanding-the-bible'
    | '/admin/notify'
    | '/admin/staff'
    | '/bible/$slug'
    | '/give/thanks'
    | '/admin/'
    | '/bible/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/assessment'
    | '/buying'
    | '/doctrine'
    | '/donate'
    | '/food-donors'
    | '/give'
    | '/happenings'
    | '/join'
    | '/login'
    | '/mission'
    | '/organizations'
    | '/pantry'
    | '/privacy'
    | '/terms'
    | '/understanding-the-bible'
    | '/admin/notify'
    | '/admin/staff'
    | '/bible/$slug'
    | '/give/thanks'
    | '/admin'
    | '/bible'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bible'
    | '/apps'
    | '/assessment'
    | '/buying'
    | '/doctrine'
    | '/donate'
    | '/food-donors'
    | '/give'
    | '/happenings'
    | '/join'
    | '/login'
    | '/mission'
    | '/organizations'
    | '/pantry'
    | '/privacy'
    | '/terms'
    | '/understanding-the-bible'
    | '/admin/notify'
    | '/admin/staff'
    | '/bible/$slug'
    | '/give/thanks'
    | '/admin/'
    | '/bible/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BibleRouteRoute: typeof BibleRouteRouteWithChildren
  AppsRoute: typeof AppsRoute
  AssessmentRoute: typeof AssessmentRoute
  BuyingRoute: typeof BuyingRoute
  DoctrineRoute: typeof DoctrineRoute
  DonateRoute: typeof DonateRoute
  FoodDonorsRoute: typeof FoodDonorsRoute
  GiveRoute: typeof GiveRouteWithChildren
  HappeningsRoute: typeof HappeningsRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MissionRoute: typeof MissionRoute
  OrganizationsRoute: typeof OrganizationsRoute
  PantryRoute: typeof PantryRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  UnderstandingTheBibleRoute: typeof UnderstandingTheBibleRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment': {
      id: '/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof AssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bible': {
      id: '/bible'
      path: '/bible'
      fullPath: '/bible'
      preLoaderRoute: typeof BibleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buying': {
      id: '/buying'
      path: '/buying'
      fullPath: '/buying'
      preLoaderRoute: typeof BuyingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctrine': {
      id: '/doctrine'
      path: '/doctrine'
      fullPath: '/doctrine'
      preLoaderRoute: typeof DoctrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-donors': {
      id: '/food-donors'
      path: '/food-donors'
      fullPath: '/food-donors'
      preLoaderRoute: typeof FoodDonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/give': {
      id: '/give'
      path: '/give'
      fullPath: '/give'
      preLoaderRoute: typeof GiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/happenings': {
      id: '/happenings'
      path: '/happenings'
      fullPath: '/happenings'
      preLoaderRoute: typeof HappeningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/understanding-the-bible': {
      id: '/understanding-the-bible'
      path: '/understanding-the-bible'
      fullPath: '/understanding-the-bible'
      preLoaderRoute: typeof UnderstandingTheBibleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/notify': {
      id: '/admin/notify'
      path: '/notify'
      fullPath: '/admin/notify'
      preLoaderRoute: typeof AdminNotifyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/bible/': {
      id: '/bible/'
      path: '/'
      fullPath: '/bible/'
      preLoaderRoute: typeof BibleIndexRouteImport
      parentRoute: typeof BibleRouteRoute
    }
    '/bible/$slug': {
      id: '/bible/$slug'
      path: '/$slug'
      fullPath: '/bible/$slug'
      preLoaderRoute: typeof BibleSlugRouteImport
      parentRoute: typeof BibleRouteRoute
    }
    '/give/thanks': {
      id: '/give/thanks'
      path: '/thanks'
      fullPath: '/give/thanks'
      preLoaderRoute: typeof GiveThanksRouteImport
      parentRoute: typeof GiveRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminNotifyRoute: typeof AdminNotifyRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminNotifyRoute: AdminNotifyRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BibleRouteRouteChildren {
  BibleSlugRoute: typeof BibleSlugRoute
  BibleIndexRoute: typeof BibleIndexRoute
}

const BibleRouteRouteChildren: BibleRouteRouteChildren = {
  BibleSlugRoute: BibleSlugRoute,
  BibleIndexRoute: BibleIndexRoute,
}

const BibleRouteRouteWithChildren = BibleRouteRoute._addFileChildren(
  BibleRouteRouteChildren,
)

interface GiveRouteChildren {
  GiveThanksRoute: typeof GiveThanksRoute
}

const GiveRouteChildren: GiveRouteChildren = {
  GiveThanksRoute: GiveThanksRoute,
}

const GiveRouteWithChildren = GiveRoute._addFileChildren(GiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BibleRouteRoute: BibleRouteRouteWithChildren,
  AppsRoute: AppsRoute,
  AssessmentRoute: AssessmentRoute,
  BuyingRoute: BuyingRoute,
  DoctrineRoute: DoctrineRoute,
  DonateRoute: DonateRoute,
  FoodDonorsRoute: FoodDonorsRoute,
  GiveRoute: GiveRouteWithChildren,
  HappeningsRoute: HappeningsRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MissionRoute: MissionRoute,
  OrganizationsRoute: OrganizationsRoute,
  PantryRoute: PantryRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  UnderstandingTheBibleRoute: UnderstandingTheBibleRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
